### PR TITLE
Update Core

### LINKED ISSUE #27: Update NUnit to version 3
See https://github.com/Particular/PlatformDevelopment/issues/792

This is small enough to fall under Maintainer Prio

### PR DESCRIPTION
**Pull request by SimonCropp**
fixes #27

### CODE REVIEW

**Comment by SimonCropp** [comment]
blocked by https://github.com/Particular/NServiceBus/pull/3775

**Comment by danielmarbach** [comment]
Merged PR in core

**Comment by SimonCropp** [comment]
@Particular/container-maintainers review+merge please

**Comment by boblangley** [comment]
Merged #28

**Pull request merged**
