### PR TITLE
Removed the acpt test source package

### PR DESCRIPTION
**Pull request by andreasohlund**

### CODE REVIEW

**Comment by andreasohlund** [comment]
@Particular/nservicebus-maintainers what do you think? (should I add some more smoke tests)

**Comment by andreasohlund** [comment]
My bad , should have pinged @Particular/container-maintainers instead

**Comment by WilliamBZA** [comment]
@andreasohlund I remember us having a plan to remove the acceptance tests from the container projects but that was put on hold until we came up with a better way to test that the containers had properly implemented RegisterSingleton.

Have we come up with a better way?

What is the context behind this PR?

**Comment by andreasohlund** [comment]
>I remember us having a plan to remove the acceptance tests from the container projects but that was put on hold until we came up with a better way to test that the containers had properly implemented RegisterSingleton.

I've missed that

>What is the context behind this PR?
I want to clean up things before I get teh property injection removal going

**Comment by andreasohlund** [comment]
This is not urgent, lets hold off until we have RegisterSingleton dealt with? (is there an issue for that)

**Comment by WilliamBZA** [comment]
@andreasohlund we have explicit RegisterSingleton tests in the container tests so I think that issue has been resolved.

We're at a stage now where all the containers  (except Spring) are passing the Container Tests as well as the Acceptance Tests.

If we remove the acceptance tests, the containers still support them as of "now". Any future changes to the containers will not be validated against the acceptance tests, and if a bug is found we should then add a repro test to the container tests. I have no doubt that we'll be able to do that, but there could be a lag period where a bug which would have been picked up by the acceptance tests slips through and we'll have to manually find it later in the process. I believe this is unlikely as I am not sure that the acceptance tests offer much more coverage for the containers than the current set of container tests.

We're also planning on transitioning away from containers.

All this being said, I am :+1: for this change. @Particular/container-maintainers what do the rest of you think?

**Comment by danielmarbach** [comment]
While I agree with the overall strategy and in long term remove the ATTs here (I even proposed it ;) ) I came to the conclusion that it is probably OK to leave them here like the other containers do and tackle this in the next release or so. So I'm on the fence. I like consistency. So if we remove them here, all other containers should also remove them.

**Comment by andreasohlund** [comment]
>So if we remove them here, all other containers should also remove them.

That was my plan since I have to touch them anyway to remove the `.ConfigureProperty`

**Comment by WilliamBZA** [comment]
No other feedback from the other maintainers, so it seems there's 1 vote to merge this and 1 on the fence. If @HEskandari and @boblangley don't have any input but tomorrow I think we'll merge this as it allows us to move forward on the `ConfigureProperty` issue.

**Comment by HEskandari** [comment]
I am on board with removing ATTs from all other containers. The only down side as @WilliamBZA stated, it'd take time to come up with container specific suit of tests that we can rely on, but since the container adapters are fairy stable, it shouldn't be a major issue IMO. :+1: on merging it in.

**Comment by danielmarbach** [comment]
When it is applied consistently I'm :+1:

**Comment by WilliamBZA** [comment]
Great, I'll submit PRs for the others in the meantime then.

**Comment by WilliamBZA** [comment]
Pull requests submitted:
 - https://github.com/Particular/NServiceBus.CastleWindsor/pull/7
 - https://github.com/Particular/NServiceBus.Autofac/pull/7
 - https://github.com/Particular/NServiceBus.Ninject/pull/16
 - https://github.com/Particular/NServiceBus.Spring/pull/14
 - https://github.com/Particular/NServiceBus.Unity/pull/28

**Comment by danielmarbach** [comment]
All merged

**Pull request merged**
