### PR TITLE
Update to StructureMap 4.1.3.394

### PR DESCRIPTION
**Pull request by bbrandt**
@WilliamBZA,
 
Also updated Fody to get past a compile error.

Since I didn't update NSB and the acceptance tests past 5.0.0, the test that was previously failing no longer exists.
Running the tests...

Replaces PR #25

### CODE REVIEW

**Comment by bbrandt** [comment]
Hi @WilliamBZA,

Any thoughts on why the Exception tests are failing for this PR?

**Comment by WilliamBZA** [comment]
@bbrandt those are from the Acceptance Tests again. It was a bright idea we had that never quite made it through.

You can delete those tests from the `Acceptance Tests` project and I'll make sure they get propagated through to the core.

**Comment by bbrandt** [comment]
@WilliamBZA Tests removed.

**Comment by malkinservicebus** [comment]
Hi @bbrandt 

Thank you for your contribution to NServiceBus code! 

We would like to send you a token of appreciation. Please forward your postal address to  operations@particular.net  so that we can send you a special gift.

**Pull request merged**
